export const PROFILE_CONFIRM_ROLES = ['STUDENT', 'PARENTS'] as const;
export const PROFILE_CONNECTION_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
} as const;
export const PROFILE_CONNECTION_STATUS_LIST = Object.values(PROFILE_CONNECTION_STATUS);

export const PROFILE_ROLES = ['STUDENT', 'PARENTS', 'INSTRUCTOR', 'ADMIN'];
