export const Symbols = {
  AuthRepository: Symbol.for('AuthRepository'),
  UsersService: Symbol.for('UsersService'),
  UsersController: Symbol.for('UsersController'),
  OrganizationsService: Symbol.for('OrganizationsService'),
  OrganizationsController: Symbol.for('OrganizationsController'),
  AuthService: Symbol.for('AuthService'),
  AuthController: Symbol.for('AuthController'),
  ClassroomsService: Symbol.for('ClassroomsService'),
  ClassroomsController: Symbol.for('ClassroomsController'),
  LecturesController: Symbol.for('LecturesController'),
  LecturesService: Symbol.for('LecturesService'),
  ProfilesService: Symbol.for('ProfilesService'),
  ProfilesController: Symbol.for('ProfilesController'),
  NoticesService: Symbol.for('NoticesService'),
  NoticesController: Symbol.for('NoticesController'),
  ConfigReader: Symbol.for('ConfigReader'),
  Database: Symbol.for('Database'),
  OrganizationsRepository: Symbol.for('OrganizationsRepository'),
  ClassroomsRepository: Symbol.for('ClassroomsRepository'),
  ProfilesRepository: Symbol.for('ProfilesRepository'),
  ProfilesLoader: Symbol.for('ProfilesLoader'),
  ClassesService: Symbol.for('ClassesService'),
  ClassesRepository: Symbol.for('ClassesRepository'),
  OrganizationOwnershipLoader: Symbol.for('OrganizationOwnershipLoader'),
};
