export const ORGANIZATION_OWNERSHIP_ROLES = {
  MAIN: 'MAIN',
  SUB: 'SUB',
} as const;

export const ORGANIZATION_OWNERSHIP_ROLE_LIST = [
  ORGANIZATION_OWNERSHIP_ROLES.MAIN,
  ORGANIZATION_OWNERSHIP_ROLES.SUB,
];
